version: "3"
services:
  mydb:
    build: ./mysql
    container_name: "mydb"
    restart: always
    networks:
      - default
    ports:
      - "3307:3306"
    volumes:
      - $PWD/mysql/conf:/etc/mysql/conf.d
      - $PWD/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=123456
  myphp:
    build: ./php
    container_name: "myphp"
    restart: always
    networks:
      - default
    ports:
      - "9001:9000"
    links:
      - "mydb"
    volumes:
      - $PWD/../www:/var/www/html
  mynginx:
    build: ./nginx
    container_name: "mynginx"
    restart: always
    networks:
      - default
    ports:
      - "8088:80"
    links:
      - "myphp"
    volumes:
      - $PWD/../www:/usr/share/nginx/html
      - $PWD/nginx/conf/:/etc/nginx:ro
      - $PWD/nginx/logs:/var/logs/nginx:rw
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "myadmin"
    restart: always
    networks:
      - default
    ports:
      - "801:80"
    links:
      - "mydb"
    environment:
      - PMA_HOSTS=mydb

networks:
  default: