version: "3"
services:
  mydb:
    build: ./mysql
    container_name: "mydb"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql/conf:/etc/mysql/conf.d
      - $PWD/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=o5UC95311O1silJ0
  myphp:
    build: ./php
    container_name: "myphp"
    restart: always
    ports:
      - "9000:9000"
    links:
      - "mydb"
    volumes:
      - $PWD/../www:/var/www/html
  mynginx:
    build: ./nginx
    container_name: "mynginx"
    restart: always
    ports:
      - "80:80"
    links:
      - "myphp"
    volumes:
      - $PWD/../www:/usr/share/nginx/html
      - $PWD/nginx/conf/:/etc/nginx:ro
      - $PWD/nginx/logs:/var/logs/nginx:rw
