version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT_0}:80"
      - "${NGINX_HTTP_HOST_PORT_1}:81"
      - "${NGINX_HTTP_HOST_PORT_2}:82"
      - "${NGINX_HTTP_HOST_PORT_3}:83"
      - "${NGINX_HTTP_HOST_PORT_4}:84"
      - "${NGINX_HTTP_HOST_PORT_5}:85"
      - "${NGINX_HTTP_HOST_PORT_6}:86"
      - "${NGINX_HTTP_HOST_PORT_7}:8081"
      - "${NGINX_HTTP_HOST_PORT_8}:8082"
      - "${WEB_SOCKET_PORT}:30000"
      - "${NGINX_HTTP_HOST_PORT_9}:88"
      - "${NGINX_HTTP_HOST_PORT_10}:89"
      - "${NGINX_HTTP_HOST_PORT_11}:99"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${LOCALTIME_DIR}:/etc/localtime:ro
      - ${TIMEZONE_DIR}:/etc/timezone:ro
    restart: always
    networks:
      - default

  php72:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP72_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php72.sh
    ports: 
      - "${WEB_SOCKET}:30000"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP72_LOG_DIR}:/var/log/php
      - ${LOCALTIME_DIR}:/etc/localtime:ro
      - ${TIMEZONE_DIR}:/etc/timezone:ro

    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default        

  php56:
    build:
      context: ./php/php56
      args:
        PHP_VERSION: ${PHP56_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php56.sh 
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
      - ${LOCALTIME_DIR}:/etc/localtime:ro
      - ${TIMEZONE_DIR}:/etc/timezone:ro
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
      - ${LOCALTIME_DIR}:/etc/localtime:ro
      - ${TIMEZONE_DIR}:/etc/timezone:ro
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${LOCALTIME_DIR}:/etc/localtime:ro
      - ${TIMEZONE_DIR}:/etc/timezone:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default
    
networks:
  default:
